apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transkriptor-data
  namespace: transkriptor
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 20Gi
