apiVersion: v1
kind: Service
metadata:
  name: local-ai
  namespace: local-ai
  labels:
    app: local-ai
spec:
  type: ClusterIP
  selector:
    app: local-ai
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
